Results will be saved in results/world_trade_1995_20240603133846
Command line input: python seal_link_pred.py --dataset world_trade_1995 --fast_split --num_hops 1 --use_feature --eval_steps 1 --epochs 10 --dynamic_train --dynamic_val --dynamic_test --train_percent 2 --val_percent 1 --test_percent 1
 is saved.
Data found, skipping download...
split_edge {'train': Data(edge_index=[2, 3486968], edge_attr=[3486968, 4], num_nodes=238, pos_edge_label=[3486968], pos_edge_label_index=[2, 3486968]), 'valid': Data(edge_index=[2, 3486968], edge_attr=[3486968, 4], num_nodes=238, pos_edge_label=[498138], pos_edge_label_index=[2, 498138]), 'test': Data(edge_index=[2, 3985106], edge_attr=[3985106, 4], num_nodes=238, pos_edge_label=[996276], pos_edge_label_index=[2, 996276])}
Type of split_edge: <class 'dict'>
split: train
split_edge keys: dict_keys(['train', 'valid', 'test'])
split_edge['train'] keys: ['pos_edge_label', 'edge_attr', 'num_nodes', 'edge_index', 'pos_edge_label_index']
Traceback (most recent call last):
  File "seal_link_pred.py", line 943, in <module>
    train_dataset = eval(dataset_class)(
  File "seal_link_pred.py", line 396, in __init__
    pos_edge, neg_edge = get_pos_neg_edges(
  File "/grphome/grp_supplychainai/SEAL_OGB/utils.py", line 330, in get_pos_neg_edges
    return pos_edge, neg_edge
UnboundLocalError: local variable 'pos_edge' referenced before assignment
