Results will be saved in results/world_trade_1995_20240722143821
Command line input: python seal_link_pred.py --dataset world_trade_1995 --fast_split --num_hops 1 --use_feature --eval_steps 1 --runs 3 --epochs 10 --dynamic_train --dynamic_val --dynamic_test --train_percent 2 --val_percent 1 --test_percent 1 --use_dl
 is saved.
Traceback (most recent call last):
  File "seal_link_pred.py", line 893, in <module>
    dataset = WorldTradeDataset(os.path.abspath("../compute/world_trade"), year=year, product_code='070200')
  File "seal_link_pred.py", line 81, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 112, in __init__
    self._download()
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 228, in _download
    fs.makedirs(self.raw_dir, exist_ok=True)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch_geometric/io/fs.py", line 55, in makedirs
    return get_fs(path).makedirs(path, exist_ok)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 58, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/grphome/grp_supplychainai/compute/world_trade'
