Results will be saved in results/world_trade_1995_20240731182121
Command line input: python seal_link_pred.py --dataset world_trade_1995 --fast_split --num_hops 1 --use_feature --eval_steps 1 --runs 3 --epochs 10 --dynamic_train --dynamic_val --dynamic_test --train_percent 2 --val_percent 1 --test_percent 1 --use_dl
 is saved.
Data found, skipping download...
Path /grphome/grp_supplychainai/nobackup/archive/world_trade_seal_h1_drnl_rph10
Total number of parameters is 89771
SortPooling k is set to 32
  0%|                                           | 0/1 [00:00<?, ?it/s]  0%|                                           | 0/1 [00:01<?, ?it/s]
z size torch.Size([799, 32])
Traceback (most recent call last):
  File "seal_link_pred.py", line 1320, in <module>
    loss = train()
  File "seal_link_pred.py", line 512, in train
    loss = BCEWithLogitsLoss()(logits.view(-1), data.y.to(torch.float))
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 731, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/grphome/grp_supplychainai/.conda/envs/sealenv/lib/python3.8/site-packages/torch/nn/functional.py", line 3224, in binary_cross_entropy_with_logits
    raise ValueError(f"Target size ({target.size()}) must be the same as input size ({input.size()})")
ValueError: Target size (torch.Size([28])) must be the same as input size (torch.Size([29]))
